export const ressource = [
  {
    title: 'Focus',
    img: 'focus.png',
    langs: ['html', 'css', 'javaScript', 'php', 'sql'],
    framework: [],
    type: ['study'],
    url: 'https://github.com/Noe-p/Developpement-application-web',
  },

  {
    title: 'Space Invaders',
    img: 'spaceInvaders.png',
    langs: ['python'],
    framework: [],
    type: ['study'],
    url: 'https://github.com/Noe-p/Space-Invaders',
  },
  {
    title: 'Angular Todo App',
    img: 'angularTodoApp.png',
    langs: ['html', 'css', 'javaScript'],
    framework: ['angular'],
    type: ['perso'],
    url: 'https://github.com/Noe-p/angular-todo-app',
  },

  {
    title: 'Todo List',
    img: 'todoApp.png',
    langs: ['html', 'css', 'javaScript'],
    framework: ['vue'],
    type: ['perso'],
    url: 'https://github.com/Noe-p/todo-list',
  },
  {
    title: 'Raconte',
    img: 'raconte.png',
    langs: ['html', 'css', 'javaScript'],
    framework: [],
    type: ['perso'],
    url: 'https://raconte-reportage.com/index.html',
  },
  {
    title: 'Batz',
    img: 'batz.png',
    langs: ['html', 'css', 'javaScript'],
    framework: [],
    type: ['perso'],
    url: 'https://location-maison-iledebatz.fr/',
  },
  {
    title: 'RPG',
    img: 'rpg.png',
    langs: ['java'],
    framework: [],
    type: ['study'],
    url: 'https://github.com/Noe-p/RPG--LPW',
  },
  {
    title: 'Pomodoro',
    img: 'pomodoro.png',
    langs: ['html', 'css', 'javaScript'],
    framework: ['react'],
    type: ['study'],
    url: 'https://pomodoro-lpw.vercel.app',
  },
];
